### ISSUE TITLE
Автопарк

### ISSUE THREAD

**Issue by Aerograch** [Aerograch/SizikovHomework#1]
@vdetstvepil 
Я сделаль

**Comment by vdetstvepil** [comment]
- 24 строка. А зачем ты конструктор сделал protected? Мы тогда из класса Program в методе main не сможем объявлять объекты класса Car, потому что к конструктору не будет доступа. Подумай, как можно исправить.
- Количество пассажиров тоже идет в конструктор класса PassengerCar.
- Поля в классе Autopark объявлены без модификаторов доступности. Это не обязательно, однако совет прописать, чтоб не вводить никого в заблуждение.

**Comment by vdetstvepil** [comment]
Исправишь косяки, приму.

**Comment by Aerograch** [comment]
> * 24 строка. А зачем ты конструктор сделал protected? Мы тогда из класса Program в методе main не сможем объявлять объекты класса Car, потому что к конструктору не будет доступа. Подумай, как можно исправить.
Я просто посчитал, что пустому конструктору можно сделать доступность protected, для того чтобы условный пользователь указывал хотя бы марку автомобиля.

> * Поля в классе Autopark объявлены без модификаторов доступности. Это не обязательно, однако совет прописать, чтоб не вводить никого в заблуждение.
А полям я просто забыл прописать protected, с непривычки.

**Comment by Aerograch** [comment]
@vdetstvepil 
Не знаю, надо ли пинговать, но я на всякий случай пингану.
Фикс я уже запушил

**Comment by vdetstvepil** [comment]
Да, нужно, а то мне уведомления не приходят. Принято.
