### ISSUE TITLE
Сделал метрополитен 1... Вроде

### ISSUE THREAD

**Issue by Aerograch** [Aerograch/SizikovHomework#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
Принято.

**Comment by vdetstvepil** [comment]
А, нет, не тот проект посмотрел) В конструкторе класса Station.cs ты присваиваешь списку ссылку на список, который является параметром. А нужно скопировать элементы из входного списка в основной. Воспользуйся циклом foreach.

**Comment by vdetstvepil** [comment]
Поправишь и зачту.

**Comment by Aerograch** [comment]
@vdetstvepil 
Все, вроде поправил

**Comment by Aerograch** [comment]
@vdetstvepil Мне закрыть Issue?
Потому что стингеры за эту задачу у меня уже есть

**Comment by vdetstvepil** [comment]
Отлично, принято.
