### ISSUE TITLE
Сделал последнюю домашку ч.1

### ISSUE THREAD

**Issue by Aerograch** [Aerograch/SizikovHomework#7]
@GalteXx

**Comment by Aerograch** [comment]
Update 1:
Сделал вторую часть

**Comment by Aerograch** [comment]
Update 2:
Сделал третью часть

**Comment by GalteXx** [comment]
Вместо ProgressBar лучше было использовать Rectange, а наследовать от UIElement

https://github.com/Aerograch/SizikovHomework/blob/186c14b7756837be5fafba95ecea861d0c731b6c/FinalWPF/FinalWPF/HorizontalHistogram.cs#L140-L148
Вот тут тебя куда-то не туда понесло. Так делать не следовало

Ну в остальном все хорошо
